# ==== pytest ====
[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--ds=config.settings.test --reuse-db --import-mode=importlib"
python_files = ["tests.py", "test_*.py"]

# ==== Coverage ====
[tool.coverage.run]
include = ["simplebuildingmanager/**"]
omit = ["*/migrations/*", "*/tests/*"]
plugins = ["django_coverage_plugin"]

# ==== mypy ====
[tool.mypy]
python_version = "3.12"
check_untyped_defs = true
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
plugins = ["mypy_django_plugin.main", "mypy_drf_plugin.main"]

[[tool.mypy.overrides]]
# Django migrations should not produce any errors:
module = "*.migrations.*"
ignore_errors = true

[tool.django-stubs]
django_settings_module = "config.settings.test"

# ==== djLint ====
[tool.djlint]
blank_line_before_tag = "load,extends,include,block"
blank_line_after_tag = "load,extends,include,block"
close_void_tags = false
format_css = false
format_js = false
preserve_leading_space = true
preserve_blank_lines = true
max_blank_lines = 5
# TODO: remove T002 when fixed https://github.com/djlint/djLint/issues/687
ignore = "H006,H030,H031,T002,H021"
include = "H017,H035"
indent = 2
max_line_length = 119
profile = "django"
ignore_blocks = "comment,translate"

[tool.djlint.css]
indent_size = 2

[tool.djlint.js]
indent_size = 2

# ==== ruff ====
[tool.ruff]
# Linting
line-length = 120

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I"]
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
extend-select = ["E501"]
fixable = ["ALL"]
ignore = ["E712", "D100", "D105", "D107", "D203", "D213", "F722", "E501"]
unfixable = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
