# Generated by Django 5.1.11 on 2025-06-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('OFFICE', 'Office'), ('RETAIL', 'Retail'), ('INDUSTRIAL', 'Industrial'), ('RESIDENTIAL', 'Residential'), ('OTHER', 'Other')], max_length=100)),
                ('area_m2', models.FloatField(help_text='Floor area in square meters')),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
