# Generated by Django 5.1.11 on 2025-06-17 04:57

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField(help_text='Use the first day of the month for monthly records')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Cost in dollars', max_digits=10)),
                ('category', models.CharField(blank=True, help_text='e.g., electricity, maintenance, gas', max_length=100)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_records', to='buildings.building')),
            ],
            options={
                'verbose_name': 'Cost Record',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['building'], name='records_cos_buildin_cbe347_idx'), models.Index(fields=['date'], name='records_cos_date_c0a943_idx')],
                'unique_together': {('building', 'date')},
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField(help_text='Use the first day of the month for monthly records')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kg_co2e', models.FloatField(help_text='Estimated or measured emissions in kilograms of CO₂e')),
                ('method', models.CharField(blank=True, help_text='e.g., calculated, metered, offset', max_length=100)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='buildings.building')),
            ],
            options={
                'verbose_name': 'Emission Record',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['building'], name='records_emi_buildin_abf332_idx'), models.Index(fields=['date'], name='records_emi_date_8ffb48_idx')],
                'unique_together': {('building', 'date')},
            },
        ),
        migrations.CreateModel(
            name='EnergyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField(help_text='Use the first day of the month for monthly records')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kwh', models.FloatField(help_text='Energy used during this period in kilowatt-hours')),
                ('source', models.CharField(blank=True, help_text='e.g., electricity, gas, solar', max_length=100)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_records', to='buildings.building')),
            ],
            options={
                'verbose_name': 'Energy Record',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['building'], name='records_ene_buildin_eacb12_idx'), models.Index(fields=['date'], name='records_ene_date_3f24ed_idx')],
                'unique_together': {('building', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WaterRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField(help_text='Use the first day of the month for monthly records')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cubic_meters', models.FloatField(help_text='Water used during this period in cubic meters')),
                ('source', models.CharField(blank=True, help_text='e.g., municipal, rainwater', max_length=100)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_records', to='buildings.building')),
            ],
            options={
                'verbose_name': 'Water Record',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['building'], name='records_wat_buildin_dd382b_idx'), models.Index(fields=['date'], name='records_wat_date_9935cf_idx')],
                'unique_together': {('building', 'date')},
            },
        ),
    ]
